### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an html skeleton.
- [x] Add a div to the form that contains the image of the car.
- [x] Change the background color of the whole page to green.
- [x] Remove styling that doesn't have a purpose.
- [x] Test functionality.
- [x] Fix errors.
