### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create 4 classes with each having the image of the car rotated.
- [x] query the image of the car.
- [x] listen for arrow button inputs on the image of the car.
- [x] make a function that changes the view of the car based on the which arrow key was pressed.
- [x] remove unnecessary styling.
- [x] check functionality.
- [x] fix errors.
