### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] create a variable that stores a boolean value whether or not the car is moving or stopped.
- [x] in the function that starts the car, make a conditional that checks if the car is stopped or not.
- [x] if the car is in motion, stop the car and save the location of the car in another variable.
- [x] if the car is stopped, then continue moving the car from the previously stopped location which should be stored in the car object.
