### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] log which direction the car is facing to the car data model.
- [x] whenever the spacebar is pressed and the car wants to move, check which direction the car is facing
- [x] if the car is facing a certain direction, move the coordinates accordingly.
- [x] create 3 more functions for moving the car north, south, and west.
